
import streamlit as st
st.set_page_config(page_title="UoM Homogeneity & Clustering Explorer", layout="wide")
st.sidebar.image("https://www.quantuniversity.com/assets/img/logo5.jpg")
st.sidebar.divider()
st.title("UoM Homogeneity & Clustering Explorer")
st.divider()
st.markdown(r"""
In this lab, we explore the critical initial step in operational risk modeling: defining appropriate Units of Measure (UoMs) and grouping diverse operational risks into homogenous units. This application allows you to generate synthetic operational loss data and apply different clustering and grouping strategies, observing their impact on data homogeneity.

The key objective is to understand how different UoM definitions affect the statistical homogeneity of the resulting data. Homogeneity is important for accurate risk modeling.

We will explore the following concepts:

*   **Units of Measure (UoMs):** Basic categories for collecting operational risk data.
*   **Homogeneity:** The statistical similarity of loss data within a UoM.
*   **Grouping Strategies:** Methods for combining raw UoMs into more homogenous groups.
*   **Kolmogorov-Smirnov (KS) Test:** A statistical test to measure the similarity between two distributions.

The application consists of three pages:

*   **Data Generation:** Generates synthetic operational loss data with customizable characteristics.
*   **UoM Grouping:** Allows you to select and apply UoM grouping strategies, including business knowledge-based grouping.
*   **Homogeneity Assessment:** Visualizes the statistical homogeneity of grouped UoMs using the Kolmogorov-Smirnov (KS) test and empirical Cumulative Distribution Functions (CDFs).


**Formulae:**

The KS D-statistic ($D$) between two empirical distributions $F_n(x)$ and $F(x)$ is defined as:
$$ D = \sup_x |F_n(x) - F(x)| $$

The scaled version for distance $d_{ij}$ between two UoMs $i$ and $j$ with sample sizes $n_i$ and $n_j$ and empirical CDFs $F_i(x)$ and $F_j(x)$ is given as:
$$ \displaystyle d_{ij}=\frac{n_i n_j}{n_i+n_j}\sup_X |F_i(x)-F_j(x)| $$
""")
# Your code starts here
page = st.sidebar.selectbox(label="Navigation", options=["Data Generation", "UoM Grouping", "Homogeneity Assessment"])
if page == "Data Generation":
    from application_pages.data_generation import run_data_generation
    run_data_generation()
elif page == "UoM Grouping":
    from application_pages.uom_grouping import run_uom_grouping
    run_uom_grouping()
elif page == "Homogeneity Assessment":
    from application_pages.homogeneity_assessment import run_homogeneity_assessment
    run_homogeneity_assessment()
# Your code ends


# License
st.caption('''
---
## QuantUniversity License

© QuantUniversity 2025  
This notebook was created for **educational purposes only** and is **not intended for commercial use**.  

- You **may not copy, share, or redistribute** this notebook **without explicit permission** from QuantUniversity.  
- You **may not delete or modify this license cell** without authorization.  
- This notebook was generated using **QuCreate**, an AI-powered assistant.  
- Content generated by AI may contain **hallucinated or incorrect information**. Please **verify before using**.  

All rights reserved. For permissions or commercial licensing, contact: [info@quantuniversity.com](mailto:info@quantuniversity.com)
''')
